# -*- coding: utf-8 -*-
import sys
import os
import json

reload(sys)  # Reload does the trick!
sys.setdefaultencoding('UTF8')

__author__ = 'chenliang'

prefix = '../../'

# var all_icons = [
#   "res/icons/1.png",
#   "res/icons/2.png"
# ];
#


with open("../../src/resource.js", "w") as icon_js:
    icon_js.write("//THIS FILE IS AUTOMATICALLY GENERATED\n//DO NOT MODIFY MANUALLY\n\n\n");
    icon_js.write("var allResource = [\n");
    all_files = []
    for path, dirlist, filelist in os.walk(prefix + "res/"):
            for file in filelist:
                if file != ".DS_Store":
                    full_path = os.path.join(path , file)
                    print full_path
                    all_files.append(full_path[len(prefix):])

    # 1. preload
    # all icons need to be loaded one record for one file
    # var resource = ["res/icons/typ1/xxx_0.png", "res/icons/typ1/xxx_2.png"];
    # 2. game logic needs random icon
    # type1 ---> 3
    # type2 ---> 4

    while len(all_files) > 0:
        path = all_files.pop()
        icon_js.write('"{0}"'.format(path))
        if len(all_files) > 0:
            icon_js.write(',')
        icon_js.write("\n")


    icon_js.write("];\n")

all_icons = {}
for path, dirlist, filelist in os.walk(prefix + "res/icons"):
    # print path, dirlist, filelist

    if not path.endswith("icons"):
        # print path, dirlist,filelist

        filtered = filter(lambda name: name.endswith("png"),filelist)
        print path[path.rindex("/")+1:],len(filtered)
        all_icons[path[path.rindex("/")+1:]] = len(filtered)

json_data = json.dumps(all_icons)
with open('../../res/all_icons.json', 'w') as outfile:
    json.dump(json_data, outfile)


